### ISSUE TITLE
Fit using test data does not match matlab fit

### ISSUE THREAD

**Issue by tomicat811** [aleksandrbazhin/ellipsoid_fit_python#2]
Hi aleks,

First, thanks for porting the matlab function to python! 

I tried fitting the test data using this python port and comparing it with the matlab function by Yury v1.3.0.0 (https://de.mathworks.com/matlabcentral/fileexchange/24693-ellipsoid-fit). However, I get a different fit using Python compared to matlab.

**Comment by aleksandrbazhin** [comment]
Hi.
I've never tested it versus Matlab function, but for me it is even not supposed to match since this port includes data regularisation and Matlab version does not. Try disabling regularisation by passing points directly to fitting function (here https://github.com/aleksandrbazhin/ellipsoid_fit_python/blob/d9c11c60a9bd36000e857088ed6035cf9ef6889e/get_calibration_ellipsoid.py#L8 ).
I wrote this code for usage with magnetometer modules and the data from them was highly irregular, so it isn't a direct port, but it looked good enough for the purpose.

**Comment by aleksandrbazhin** [comment]
Any updates? Did you try disabling regularisation?

**Comment by foobarbecue** [comment]
I've tried this with and without regularization and the results seem to be rotated incorrectly. Here's an example with the regularization disabled:

Python version:
![image](https://user-images.githubusercontent.com/854789/53706699-63edac80-3de0-11e9-94d5-2bf92a3ef5a6.png)

Matlab version:
![image](https://user-images.githubusercontent.com/854789/53706751-a8794800-3de0-11e9-8196-ccdb2048916d.png)

**Comment by aleksandrbazhin** [comment]
Can you please send your data, I will try to fix it.
Also add please result from matlab (center, radii, eigenvecs, v)

**Comment by foobarbecue** [comment]
Great! The data used here is:

[test_data.txt](https://github.com/aleksandrbazhin/ellipsoid_fit_python/files/2924240/test_data.txt)

Matlab output is:

Ellipsoid center: -0.35549 0.099611 -0.31471
Ellipsoid radii: 0.33903 0.1512 0.026977
Ellipsoid evecs:
0.077342 0.75427 0.65199
0.99545 -0.021967 -0.092672
0.055578 -0.65619 0.75254
Algebraic form:
-0.3256 -4.0776 -5.3462 0.34556 -0.3682 4.6076 -0.26604 1.9791 -2.2723 -1 
Average deviation of the fit: 0.72301

It's not particularly well-suited for this kind of fitting I guess, because I only actually have data for half of the ellipsoid surface. I was thinking about trying to adapt the code to solve a "half-ellipsoid." I noticed that the matlab version is solving the 9-dof version of the problem.

**Comment by foobarbecue** [comment]
Ok I actually just found https://github.com/marksemple/pyEllipsoid_Fit which matches the results from the matlab code (https://www.mathworks.com/matlabcentral/fileexchange/24693-ellipsoid-fit)

**Comment by aleksandrbazhin** [comment]
Great! I will try to fix it nevertheless. As for half-ellipsoid problem you can just quick hack it by mirroring data over a plane to get full ellipsoid=) Seems like the largest axis found by full-ellipsoid solvers is ok, so it shouldn't be hard to find a plane.

**Comment by aleksandrbazhin** [comment]
Fixed the solution. Will upload soon.
![figure_1](https://user-images.githubusercontent.com/875308/53713729-9d352380-3e97-11e9-8bf2-e6e852c4425a.png)
Also I believe that https://github.com/marksemple/pyEllipsoid_Fit has eigenvectors transposed due to difference between numpy.eig and Matlab eig.
